In [4]:
import numpy as np
CONST_K=9e9
np.set_printoptions(suppress=True, formatter={'float_kind':'{:.4e}'.format})


In [5]:
def vector_unitario(point1, point2):
    print(f"norma = {np.linalg.norm(point2-point1)} vector = {(point2-point1)}")
    return (point2-point1)/np.linalg.norm(point2-point1) 

def angulo_vectores(v1, v2):
    return 180*(1/np.pi)*np.arccos(
            np.dot(v1,v2)/(np.linalg.norm(v1)*np.linalg.norm(v2))
        )
        
def campo_electrico_linea(lamda, angulo1, angulo2, a):
    global CONST_K
    angulo1=(np.pi/180)*angulo1
    angulo2=(np.pi/180)*angulo2
    return  np.abs( (CONST_K*lamda/a)*(np.cos(angulo2)-np.cos(angulo1)))


In [3]:
_A = np.array([0,4,0])
_B = np.array([0,4,3])
_C = np.array([3,0,3])
_D = np.array([-3,0,3])
_E = np.array([-3,0,-3])
_F = np.array([3,0,-3])
_G = np.array([0,0,3])
_H = np.array([-3,0,0])
_I = np.array([0,0,-3])
_J = np.array([3,0,0])

In [19]:
v_lambda = (-1/3)*1e-6
r = 5e-4

In [6]:
#Se calculan los angulos
v_i = np.array([1,0,0])
v_j = np.array([0,1,0])
v_k = np.array([0,0,1])

angulo_vectores(v_i, vector_unitario(_F,_B))

norma = 7.810249675906654 vector = [-3  4  6]


112.58853878798487

In [38]:
v_lambda = -(1/3)*1e-6
a =np.sqrt(52)*1e-2
print("%.4e" % campo_electrico_linea(v_lambda,  180-67.41, 67.41,    a))

3.1962e+04


In [39]:
print(3.1962e+04*vector_unitario(_B, _I))


norma = 7.211102550927978 vector = [ 0 -4 -6]
[0.0000e+00 -1.7729e+04 -2.6594e+04]


In [135]:
campo_electrico_linea(v_lambda, 59.04, 180-59.04,  a)*vector_unitario(_A, _G)+campo_electrico_linea(v_lambda, 59.04, 180-59.04,  a)*vector_unitario(_A, _H)+campo_electrico_linea(v_lambda, 59.04, 180-59.04,  a)*vector_unitario(_A, _I)+campo_electrico_linea(v_lambda, 59.04, 180-59.04,  a)*vector_unitario(_A, _J)

norma = 5.0 vector = [ 0 -4  3]
norma = 5.0 vector = [-3 -4  0]
norma = 5.0 vector = [ 0 -4 -3]
norma = 5.0 vector = [ 3 -4  0]


array([0.0000e+00, -1.9754e+05, 0.0000e+00])

In [36]:
np.array([0,-9e4,0])+np.array([0, -1.7729e+04, -2.6594e+04])+np.array([2.7654e+04, -3.6872e+04, 0])+np.array([-2.7654e+04, -3.6872e+04, 0])

array([0.0000e+00, -1.8147e+05, -2.6594e+04])

In [14]:
vector_unitario(_B,_C)


norma = 5.0 vector = [ 3 -4  0]


array([ 0.6, -0.8,  0. ])